version: '2'
services:
  test1jhipsterapp-postgresql:
    image: postgres:11.4
    # volumes:
    #     - ~/volumes/jhipster/test1jHipsterApp/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test1jHipsterApp
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
